# generated by datamodel-codegen:
#   filename:  source.yaml
#   timestamp: 2025-07-19T20:12:38+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class AccountId(RootModel[str]):
    root: str = Field(..., pattern='^[0-9]{12}$')


class Region(RootModel[str]):
    root: str = Field(..., pattern='^[a-z0-9-]+$')


class Filters(BaseModel):
    account_ids: Optional[List[AccountId]] = Field(
        None, description='List of AWS account IDs to include'
    )
    regions: Optional[List[Region]] = Field(
        None, description='List of AWS regions to include'
    )
    organizational_units: Optional[List[str]] = Field(
        None, description='List of AWS organizational unit IDs to include'
    )


class Type(Enum):
    aws_assume_role = 'aws_assume_role'


class AwsAssumeRoleConfig(BaseModel):
    role_arn: str = Field(
        ...,
        description='ARN of the IAM role to assume in target accounts',
        pattern='^arn:aws:iam::[0-9]{12}:role/.+',
    )
    external_id: Optional[str] = Field(
        None,
        description='Optional external ID for assume role (recommended for security)',
    )
    session_name: Optional[str] = Field(
        None, description='Optional custom session name for AssumeRole API'
    )
    permissions_boundary_check: Optional[bool] = Field(
        False, description='Whether to validate permissions boundaries before assuming'
    )


class ScanTool(BaseModel):
    type: Type = Field(..., description='Type of scan tool')
    configuration: AwsAssumeRoleConfig


class AwsConfig(BaseModel):
    management_account_id: str = Field(
        ..., description='AWS account ID that manages the source', pattern='^[0-9]{12}$'
    )
    filters: Optional[Filters] = None
    scan_tools: Optional[List[ScanTool]] = Field(
        None, description='List of scan tools to use for this source'
    )


class Source(BaseModel):
    id: str = Field(..., description='Unique identifier for the source')
    name: str = Field(..., description='Human-readable name for the source')
    config: AwsConfig


# Response wrapper models

class SourcesResponse(BaseModel):
    sources: List[Source] = Field(..., description='List of source objects')